name: Trigger Continuous Analysis

on:
  workflow_dispatch:
    inputs:
      commit:
        description: 'Single commit SHA to test'
        required: true
        type: string

permissions:
  actions: read
  contents: write
  issues: write

jobs:
  analyze-single-commit:
    uses: ContinuousAnalysis/continuous-analysis/.github/workflows/auto-runner.yml@main
    with:
      project: ${{ github.repository }}
      commit: ${{ inputs.commit }}
    secrets:
      ORG_WIDE_TOKEN: ${{ secrets.ORG_WIDE_TOKEN }}